version: '3.7'

services:

  redis:
    container_name: 'dmb-api-redis'
    restart: 'always'
    build:
      context: '.docker/redis'
    ports:
      - '6379:6379'
    volumes:
      - 'redis-data:/data'
      - './logs:/var/log'
    networks:
      - 'dmb-api-net'

networks:
  dmb-api-net:

volumes:
  redis-data:
